# Generated by Django 4.1.7 on 2023-05-31 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academicos', '0004_alumno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('idMatricula', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('fechaMat', models.DateField()),
                ('cuotas', models.IntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academicos.curso')),
            ],
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
    ]
