# Generated by Django 4.1.7 on 2023-05-31 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academicos', '0005_matricula_delete_alumno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='curso',
            new_name='cursos',
        ),
    ]
